a = int(input("Enter the number1:"))
b = int(input("Enter the number2:"))
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Modulus:",a%b)